packageExtensions:
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  "@graphql-codegen/cli@*":
    dependencies:
      ts-node: "*"
  cosmiconfig-typescript-loader@*:
    peerDependencies:
      ts-node: "*"
  eslint-config-next@*:
    dependencies:
      next: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
